### ISSUE TITLE
Todolist

### ISSUE THREAD

**Issue by stoeffel** [stoeffel/1-liners#1]
- [x] and
- [x] bitAnd
- [x] or
- [x] bitOr
- [x] not
- [x] compose
- [x] nand
- [x] nor
- [x] nth
- [x] noop
- [x] apply
- [x] pipe
- [x] length
- [x] inc
- [x] dec
- [x] equal
- [x] looseEqual
- [ ] lt
- [ ] gt
- [ ] le
- [ ] ge
- [ ] bind
- [ ] call
- [ ] has
- [ ] converge
- [ ] isString
- [ ] isObject
- [ ] isBoolean
- [ ] isNumber
- [ ] isInt
- [ ] isPlainObject
- [ ] plus
- [ ] minus
- [ ] times (I don’t like this name)
- [ ] by
- [ ] isTrue
- [ ] isFalse
- [ ] isNull
- [ ] isUndefined

### Function
- [x] curry1,2,3,4

### Array functions
- [x] filter(function, array)
- [x] reduce(function, array)
- [x] every(function, array)
- [x] some(function, array)
- [x] reduceRight(function, array)
- [x] reduceFrom(function, initialValue, array)
- [x] reduceRightFrom(function, initialValue, array)
- [ ] forEach(function, array)

### String functions
- [x] join(string, array)
- [x] split(splitStr, string)
- [ ] word
- [ ] csv

### RegExp
- [ ] replace(regEx, string)
- [ ] match(regEx, string)

**Comment by hemanth** [comment]
I have implemented bit-wise operations ;)

**Comment by stoeffel** [comment]
How about renaming them to bitAnd, bitOr...?

**Comment by hemanth** [comment]
@stoeffel Done.

**Comment by hemanth** [comment]
@stoeffel How are you planning to implement `deepEqual` in one line? `JSON.stringify`? `assert.deepEqual` ;) ??

**Comment by stoeffel** [comment]
> How are you planning to implement deepEqual in one line?

hihi, don't know. This is just a list of things that came to my mind.

**Comment by tomekwi** [comment]
How about functionizing string and array functions, like you did with `map`? I mean:

- `replace(regEx, string)`
- `match(regEx, string)`
- `split(splitStr, string)`
- `reduce(function, array)`
- `reduceFrom(function, initialValue, array)`
- `join(string, array)`
- `forEach(function, array)`
- …

That’s what I meant in <https://github.com/stoeffel/1-liners/pull/10#issuecomment-95158332>.

**Comment by stoeffel** [comment]
> How about functionizing string and array functions, like you did with map

:+1: Yop that's what I was thinking too. Let's add them to the todolist. I have to sleep now, will have some time tomorrow evening.

**Comment by tomekwi** [comment]
How about:
- `isString`
- `isObject`
- `isBoolean`
- `isNumber`
- (no need to duplicate `Array.isArray`)
- `isInt`
- `isPlainObject`

**Comment by stoeffel** [comment]
:+1: what is the difference between isObject and isPlainObject?

**Comment by tomekwi** [comment]
* https://lodash.com/docs#isObject
* https://lodash.com/docs#isPlainObject

**Comment by stoeffel** [comment]
Thanks for the links.
Let's add this functions to 1-liners.

**Comment by tomekwi** [comment]
https://github.com/stoeffel/1-liners/pull/30#issue-72239642

```js
const sum = (numbers) => numbers.reduce((a, b) => a + b);
```

the `(a, b) => a + b` would fit into *1-liners* well, wouldn’t it?

How about:

* `plus`
* `minus`
* `times` (I don’t like this name)
* `by`

**Comment by tomekwi** [comment]
https://github.com/stoeffel/1-liners/pull/31

If these go through, it’d be good to have the following as well:

- `isTrue`
- `isFalse`
- `isNull`
- `isUndefined`

**Comment by tomekwi** [comment]
One more idea. How about these:

- `property`:  
`(object, property) => object[property]`

- `method`:  
`(object, method) => (...args) => object[method](...args)`

**Comment by tomekwi** [comment]
> - equal
> - strictEqual

How about
- `looseEqual`
- `equal`?

The JS community seems to prefer `===` over `==` – see for example https://github.com/airbnb/javascript#comparison-operators--equality (the most popular coding style by all means).

**Comment by stoeffel** [comment]
This all sounds great. You are a :rocket:! I hope I will have some time tomorrow to jump in on this.

**Comment by tomekwi** [comment]
Haha, thanks :D Take it easy @stoeffel – take your time :)

**Comment by tomekwi** [comment]
BTW, I’m just working on another project and whenever I need a little tool I put it here instead of there :)

**Comment by stoeffel** [comment]
> BTW, I’m just working on another project and whenever I need a little tool I put it here instead of there :)

cool.

> I have a tomekwi/1-liners#edge for things I need quick :)

Feel free to just publish to npm.

**Comment by stoeffel** [comment]
> looseEqual
equal?

Yop, in my opinion this should always be the default.

**Comment by stoeffel** [comment]
I will close this in favour of individual issues, to be apple to keep track of development.
