### ISSUE TITLE
Curry all the things

### ISSUE THREAD

**Issue by stoeffel** [stoeffel/1-liners#17]
How do you feel about adding a step to the prepublish task to create a folder `./curry` with all the functions curryied.
So a user can require i.e.
```js
var ifElse = require('1-liners/curry/ifElse');
ifElse(cond)(then)(otherwise);
```

The generated modules in `curry` would look like this:
```js
var curry = require('../curry3'); // 1, 2, 3 or 4 the task needs to check the length of the function
module.exports = curry(require('../ifElse'));
```
// cc @hemanth @tomekwi @tristaaan

**Comment by hemanth** [comment]
:+1:

**Comment by tomekwi** [comment]
TBH, I actually liked how we don’t make assumptions about how a function should be curried like *101* does. It makes the lib feel super lightweight.

I guess that’s not less readable:

```js
var ifElse = require('1-liners/curry3')(require('1-liners/ifElse'));
```

**Comment by tomekwi** [comment]
Off topic: what’s the purpose of *1-liners/curry1*?

**Comment by stoeffel** [comment]
> don’t make assumptions

good point.

> Off topic: what’s the purpose of 1-liners/curry1?

The purpose of `curry1` is the following:
```js
var curry1 = require('./src/curry1');
var curry2 = require('./src/curry2');
var map = curry2(require('./src/map'));

var notCurryied = map(parseInt);
var curryied = map(curry1(parseInt));

console.log(notCurryied( [1.1, 2.2, 3.3, 4.4, 5.5, 6.6] ));
console.log(curryied( [1.1, 2.2, 3.3, 4.4, 5.5, 6.6] ));
```

Outputs:
```bash
$ babel-node exampleCurry1.js
[ 1, NaN, NaN, NaN, NaN, NaN ]
[ 1, 2, 3, 4, 5, 6 ]
```

**Comment by stoeffel** [comment]
Closed to stay `super lightweight`

**Comment by tomekwi** [comment]
:+1: 

> The purpose of curry1 is the following

Wow! JavaScript, you’ve always far surpassed my wildest expectations :)
