### ISSUE TITLE
A way to pull in the whole lot

### ISSUE THREAD

**Issue by tomekwi** [stoeffel/1-liners#32]
When size doesn’t matter, you’d sometimes just want to save 5 lines of code and write:

```js
import {flip, curry2, split, and, or, isTruthy} from '1-liners/module';
```

Here’s one way to do it – which works both for `require` and the ES6 `import`:
- [`module.js`](https://github.com/tomekwi/virtual-dom-lite/blob/0bc3/module.js)
- [`module/index.js`](https://github.com/tomekwi/virtual-dom-lite/blob/0bc3/module/index.js)

**Comment by stoeffel** [comment]
SGTM. We could add a npm task to update the module/index with all modules.

**Comment by tomekwi** [comment]
:+1:
