### ISSUE TITLE
Idea: have only one simple curry function

### ISSUE THREAD

**Issue by tomekwi** [stoeffel/1-liners#44]
```js
import curry from '1-liners/curry2';

const f = (a, b, c, d) => a * b - c * d + e;
const fβ = curry(f)                       // ~= curry2       
const fγ = curry(curry(f))                // ~= curry3                
const fδ = curry(curry(curry(f)))         // ~= curry4                           
const fε = curry(curry(curry(curry(f))))  // ~= curry5

f(1, 2, 3, 4, 5)  === -5

fβ(1)(2, 3, 4, 5) === -5
fβ(1, 2)(3, 4, 5) === -5
fβ(1, 2, 3)(4, 5) === -5
fβ(1, 2, 3, 4)(5) === -5

fγ(1)(2)(3, 4, 5) === -5
fγ(1)(2, 3)(4, 5) === -5
fγ(1, 2)(3, 4)(5) === -5

fδ(1)(2)(3)(4, 5) === -5
fδ(1)(2)(3, 4)(5) === -5
fδ(1)(2, 3)(4)(5) === -5
fδ(1, 2)(3)(4)(5) === -5

fε(1)(2)(3)(4)(5) === -5
```

Let’s just leave `curry2` and name it `curry`.

Less is more.

**Comment by hemanth** [comment]
`nCurry` ftw?

**Comment by stoeffel** [comment]
:+1: for naming it curryN. I think we can keep the fixed curryies. I think curryN is nice but sometimes I don't want to rely on the length of the function.

**Comment by tomekwi** [comment]
What I suggest is to keep only a fixed curry – `curry2` without any modifications.

Anything can be done with that, as I showed at the beginning. And we want to keep it dead simple, don’t we?

**Comment by stoeffel** [comment]
Yop, you are right. with the current implementation of curry2 this is possible. Lets do this and update the docs to show how you do curry3,4...

**Comment by tomekwi** [comment]
:+1:

Then we’ll also do the same with `uncurry` and `curryRight`, shouldn’t we?

@stoeffel @hemanth do you think it’s reasonable to keep the name `curry2` or rename it to `curry`? I’d go for `curry`.

BTW, I can’t remember a situation when I really needed anything more than `curry2` :)

**Comment by stoeffel** [comment]
Yes, it should be consistent so let's do the same for uncurry and
curryRight. I would rename curry2 to curry. I can't remember a situation
either:-)
Am 05.05.2015 12:42 schrieb "Tomek Wiszniewski" <notifications@github.com>:

**Comment by stoeffel** [comment]
Or one could use `compose` and `reduce`.

```js
import curry from '1-liners/curry2';
import reduce from '1-liners/reduce';
import compose from '1-liners/compose';

const curry3 = compose(curry, curry);
const curry4 = reduce(compose, [curry, curry, curry]);

const f = (a, b, c, d) => a * b * c * d;
const fβ = curry(f)                       // ~= curry2       
const fγ = curry3(f)                // ~= curry3
const fδ = curry4(f)                // ~= curry4

f(1, 2, 3, 4)  === 24

fβ(1)(2, 3, 4) === 24
fβ(1, 2)(3, 4) === 24
fβ(1, 2, 3)(4) === 24

fγ(1)(2)(3, 4) === 24
fγ(1)(2, 3)(4) === 24

fδ(1)(2)(3)(4) === 24
```

**Comment by tomekwi** [comment]
:+1:
