### ISSUE TITLE
Mark as unstable

### ISSUE THREAD

**Issue by tomekwi** [stoeffel/1-liners#45]
There’s lots of fiery development going on at the moment. I know the `0.x` semver version already means the same – but why not warn people even so?

How about one of these ugly guys <https://github.com/badges/stability-badges>:

[![unstable](http://badges.github.io/stability-badges/dist/unstable.svg)](http://github.com/badges/stability-badges)

Or some prettier ones <http://shields.io>:

[![Stability: unstable](https://img.shields.io/badge/stability-unstable-yellowgreen.svg)](https://nodejs.org/api/documentation.html#documentation_stability_index) [![Stability: unstable](https://img.shields.io/badge/stability-unstable-yellowgreen.svg?style=flat-square)](https://nodejs.org/api/documentation.html#documentation_stability_index)

This way taking off the “unstable” badge will be a point to look forward to and celebrate :D

**Comment by stoeffel** [comment]
Sure lets add that and start a roadmap for 1.0.0 We should split up the todolist issue and add them to the milestone. I will have some time this afternoon.

**Comment by stoeffel** [comment]
add one from shield.io not the ugly one :smile:

**Comment by tomekwi** [comment]
:+1:

**Comment by hemanth** [comment]
Can I get a shirt that says: "unstable" ;) :+1:
