### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by stoeffel** [stoeffel/1-liners#46]
Which one do you like guys? Feedback?

@hemanth 
- [ ] green 
- [x] red

@tomekwi 
- [ ] green 
- [x] red

@stoeffel
- [ ] green 
- [X] red

I have just one revision at fiverr and I will get it as a SVG.

| green | red |
| --- | --- |
| ![1liners01](https://cloud.githubusercontent.com/assets/1217681/7472162/c32cbbd2-f32f-11e4-8cac-44e411c48189.png) | ![1liners02](https://cloud.githubusercontent.com/assets/1217681/7472164/c5f4a136-f32f-11e4-9e27-9242c5e8f655.png) |
| ![1liners01](https://cloud.githubusercontent.com/assets/1217681/7472165/c7997796-f32f-11e4-83db-b27bce136911.jpg) | ![1liners02](https://cloud.githubusercontent.com/assets/1217681/7472166/c8db1f24-f32f-11e4-9d90-e84ea3b4a786.jpg) |

**Comment by tomekwi** [comment]
Red looks great – but I don’t quite get what it shows :)

**Comment by stoeffel** [comment]
> Red looks great – but I don’t quite get what it shows :)

haha, I guess lines of code. Do you have any input? colors? Font?
else I will complete the order.

**Comment by tomekwi** [comment]
I like the colors, font and style. I don’t like how it looks complicated.

**Comment by tomekwi** [comment]
The way the red lines encapsulate all that code makes this feel like a framework rather than a slim library.

**Comment by stoeffel** [comment]
> I don’t like how it looks complicated.

That's what I like about the first one, it's simple.

> But even so it looks great :)

Me too.

**Comment by stoeffel** [comment]
So let's go with the red one. All agreed?

**Comment by stoeffel** [comment]
What about, if the read line around the 1 wouldn't break?

**Comment by tomekwi** [comment]
Ahhhh, now I see the the 1 :)

Here’s what we could do. A quick one.

![1l](https://cloud.githubusercontent.com/assets/4624660/7474073/6be1ee1e-f33f-11e4-8c37-5c2641070e72.png)

**Comment by stoeffel** [comment]
Yop. I like this!  I will bump this to the guy from fivrr.
