### ISSUE TITLE
Moving documentation to jsdoc

### ISSUE THREAD

**Issue by stoeffel** [stoeffel/1-liners#53]
```
/**
 * @module and
 * 
 * Same as `a && b`.
 *
 * @example
 *   var and = require('1-liners/and');
 * 
 *   and(true, true); // => true
 *   and(false, true); // => false
 */
export default (x, y) => x && y;
```

**Comment by stoeffel** [comment]
Do we need `@params` or other annotations?

**Comment by tomekwi** [comment]
We can have them in (for IDEs and such) but not render them in the readme.

**Comment by stoeffel** [comment]
I actually like having a markdown with all the docs. We could render them in a documentation.md and link it in the readme

**Comment by tomekwi** [comment]
I’m good either way :)

**Comment by stoeffel** [comment]
@hemanth what do you think?

**Comment by hemanth** [comment]
`documentation.md ` is also a good way.

**Comment by tomekwi** [comment]
we can also do a `documentation/Readme.md` – and split it into multiple files when it gets too fat.

**Comment by stoeffel** [comment]
Let's go with document/readme.md
