### ISSUE TITLE
adding pre-commit

### ISSUE THREAD

**Issue by stoeffel** [stoeffel/1-liners#56]
How about we add [pre-commit](https://github.com/observing/pre-commit) to ensure that `npm run toc` and `npm run test` is run before commiting?

**Comment by tomekwi** [comment]
https://github.com/typicode/husky

**Comment by stoeffel** [comment]
I like husky

**Comment by tomekwi** [comment]
Then let’s do it :)

**Comment by stoeffel** [comment]
:rocket:
