### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by stoeffel** [stoeffel/1-liners#8]
- [x] TOC in the readme
- [x] add them as owners
- [ ] create a nice logo (WIP)
- [x] contributors list

**Comment by stoeffel** [comment]
@tomekwi @hemanth I added you guys as owners feel free to push as you like or create a PR if you want feedback. But don't feel obligated:smile:

**Comment by hemanth** [comment]
:tongue: Sure!

**Comment by tomekwi** [comment]
Wow, thanks :D

**Comment by stoeffel** [comment]
We should state somewhere in the readme that the whole thing is build out of oneliner functions.

**Comment by stoeffel** [comment]
I close this since only logo is left and  that will come.

**Comment by hemanth** [comment]
:+1:
